db-uri = "postgres://postgres@localhost:5432/lis_local"
db-schemas = "public"
db-anon-role = "postgres"
server-host = "0.0.0.0"
server-port = 8000
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
jwt-secret-is-base64 = false
